"use client";

import Image from "next/image";
import { motion, useInView } from "motion/react";
import { useTheme } from "next-themes";
import { useEffect, useRef, useState } from "react";

const fadeUp = { hidden: { opacity: 0, y: 28 }, visible: { opacity: 1, y: 0 } };
function Reveal({ children, className = "", delay = 0 }: { children: React.ReactNode; className?: string; delay?: number }) { const ref = useRef(null); const inView = useInView(ref, { once: true, margin: "-12%" }); return <motion.div ref={ref} className={className} variants={fadeUp} initial="hidden" animate={inView ? "visible" : "hidden"} transition={{ duration: 0.8, delay, ease: [0.22, 1, 0.36, 1] }}>{children}</motion.div>; }
function InkLoader({ onDone }: { onDone: () => void }) { const [started, setStarted] = useState(false); const [origin, setOrigin] = useState({ x: 50, y: 50 }); const begin = (event: React.MouseEvent<HTMLDivElement>) => { if (started) return; const rect = event.currentTarget.getBoundingClientRect(); setOrigin({ x: ((event.clientX - rect.left) / rect.width) * 100, y: ((event.clientY - rect.top) / rect.height) * 100 }); setStarted(true); window.setTimeout(onDone, 2900); }; const onKeyDown = (event: React.KeyboardEvent<HTMLDivElement>) => { if ((event.key === "Enter" || event.key === " ") && !started) { event.preventDefault(); setStarted(true); window.setTimeout(onDone, 2900); } }; return <div className={`ink-loader ${started ? "ink-started" : ""}`} onClick={begin} onKeyDown={onKeyDown} tabIndex={0} aria-label="点击进入" role="button" style={{ "--origin-x": `${origin.x}%`, "--origin-y": `${origin.y}%` } as React.CSSProperties}><div className="paper-grain" /><div className="ink-message"><strong>凡客至此，幸会</strong><span>{started ? "水墨入境" : "点击屏幕入境"}</span></div><div className="ink-veil" /><div className="ink-ripple ripple-one" /><div className="ink-ripple ripple-two" /><div className="ink-blob blob-a" /><div className="ink-blob blob-b" /><div className="ink-blob blob-c" /><div className="ink-blob blob-d" /></div>; }
function ThemeRipple() { const { resolvedTheme, setTheme } = useTheme(); const [mounted, setMounted] = useState(false); const [ripples, setRipples] = useState<{ id: number; x: number; y: number }[]>([]); useEffect(() => setMounted(true), []); const toggle = (event: React.MouseEvent<HTMLButtonElement>) => { const rect = event.currentTarget.getBoundingClientRect(); const id = Date.now(); setRipples((items) => [...items, { id, x: rect.left + rect.width / 2, y: rect.top + rect.height / 2 }]); window.setTimeout(() => setRipples((items) => items.filter((item) => item.id !== id)), 850); setTheme(resolvedTheme === "dark" ? "light" : "dark"); }; const isDark = mounted && resolvedTheme === "dark"; return <><button className="theme-button" onClick={toggle} aria-label="切换明暗主题"><span className="theme-orb">{mounted ? (isDark ? "☼" : "◐") : "◌"}</span><span>{mounted ? (isDark ? "入昼" : "入夜") : "主题"}</span></button>{ripples.map((ripple) => <span key={ripple.id} className="theme-ripple" style={{ left: ripple.x, top: ripple.y }} />)}</>; }

export function BlogHome() { const [loading, setLoading] = useState(true); const [menuOpen, setMenuOpen] = useState(false); const [pointer, setPointer] = useState({ x: 50, y: 50 }); return <><div className={`site-shell ${loading ? "is-loading" : ""}`}><header className="site-header"><a className="brand" href="#top"><span className="brand-mark">墨</span><span>守静致虚</span></a><nav className={menuOpen ? "nav-open" : ""}><a href="#about">关于</a><a href="#craft">技艺</a><a href="#journal">札记</a><a href="#contact">联系</a></nav><div className="header-actions"><ThemeRipple /><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="打开菜单">{menuOpen ? "×" : "☰"}</button></div></header>
<main id="top"><section className="hero-section"><video className="hero-video" autoPlay muted loop playsInline poster="/media/avatar.jpg"><source src="/media/ink-background.mp4" type="video/mp4" /></video><div className="hero-wash" /><div className="mist mist-a" /><div className="mist mist-b" /><div className="hero-content"><p className="eyebrow">PERSONAL NOTEBOOK · 2026</p><h1>守静<span>致虚</span></h1><p className="hero-lead">软件开发者 · 创意编程实践者 · 技术写作者</p><p className="hero-intro">吾名守静致虚，习技之人。以代码为笔，以体验为墨，在前端、后端、移动与云端之间，记录每一次思考与创造。</p><a className="ink-link" href="#about">向下探索 <span>↓</span></a></div><div className="hero-seal">虚静<br />以通</div></section>
<section id="about" className="section about-section"><Reveal className="section-kicker">01 / ABOUT</Reveal><div className="about-grid"><Reveal><div className="portrait-frame"><Image src="/media/avatar.jpg" alt="守静致虚头像" width={940} height={940} priority /><span className="portrait-caption">墨青 · 其一</span></div></Reveal><Reveal delay={0.12}><div><p className="section-kicker">关于我</p><h2>把复杂的事，<em>做得优雅。</em></h2><p className="body-copy">用户体验为本，代码视为艺，求精求雅；常怀好奇，日学不辍；乐与开源，知无不言。遇事求新，不拘故常。</p><p className="body-copy">曾为企业构建内部系统，亦维护开源数件。私暇自研小作，试验新思；也在文字中整理项目得失与架构之道。</p><div className="quote">“虚静以通，神明其德。”</div></div></Reveal></div></section>
<section id="craft" className="section craft-section"><Reveal className="section-kicker">02 / CRAFT</Reveal><Reveal><h2>技之所重，<em>在于通达。</em></h2></Reveal><div className="craft-grid">{[['01','前端开发','Vue.js 3 · React · Qwik · SolidJS','TypeScript / Vite / Webpack / Rollup'],['02','后端开发','Rust · Node.js · Python · Go','RESTful API / GraphQL / 微服务'],['03','移动开发','Flutter · React Native · Tauri','Kotlin / Swift / 性能优化'],['04','开发工具','Git · GitHub Actions · GitLab CI','ESLint / Prettier / 敏捷协作']].map(([no,title,desc,sub], i) => <Reveal key={no} delay={i * 0.08}><article className="craft-card"><span>{no}</span><h3>{title}</h3><p>{desc}</p><small>{sub}</small></article></Reveal>)}</div></section>
<section id="journal" className="section journal-section"><Reveal className="section-kicker">03 / JOURNAL</Reveal><div className="journal-heading"><Reveal><h2>写作之余，<em>亦喜笔耕。</em></h2></Reveal><Reveal delay={0.1}><p className="body-copy">或撰教程，或记项目得失，或论架构之道，或录生活所感。</p></Reveal></div><div className="journal-list">{[['01','项目阅历','曾为企业建内部系统，亦维护开源数件'],['02','写作之余','或撰教程，或记项目得失，或论架构之道'],['03','社区参与','参与社区，贡献薄力']].map(([no,tag,title], i) => <Reveal key={no} delay={i * 0.08}><a className="journal-item" href="#contact"><span>{no}</span><div><small>{tag}</small><h3>{title}</h3></div><span className="journal-arrow">↗</span></a></Reveal>)}</div></section>
<section id="contact" className="section contact-section"><Reveal className="section-kicker">04 / CONTACT</Reveal><Reveal><h2>愿与你，<em>以诚相见。</em></h2><p className="body-copy">如果你对我的工作感兴趣，或者有任何问题、建议，欢迎通过以下方式联系我。</p><a className="contact-mail" href="mailto:1755070122@qq.com">1755070122@qq.com <span>↗</span></a><div className="contact-links"><a href="https://github.com/kar32224-png" target="_blank" rel="noreferrer">GitHub / kar32224-png</a><span>感谢拨冗垂阅，愿有所益。</span></div></Reveal></section></main><footer><span>© 2026 守静致虚</span><span>墨青水墨 · 东方美学与现代技术</span></footer></div>{loading && <InkLoader onDone={() => setLoading(false)} />}</>; }
