"use client";
import Image from "next/image";
import { motion, useInView } from "motion/react";
import { useRef } from "react";

function Reveal({ children, delay = 0 }: { children: React.ReactNode; delay?: number }) { const ref = useRef(null); const visible = useInView(ref, { once: true, margin: "-10%" }); return <motion.div ref={ref} initial={{ opacity: 0, y: 24 }} animate={visible ? { opacity: 1, y: 0 } : { opacity: 0, y: 24 }} transition={{ duration: .7, delay }}>{children}</motion.div>; }

export function BlogHomeV2() { return <div className="blog-v2"><header className="site-header"><a className="brand" href="#top"><span className="brand-mark">墨</span><span>守静致虚</span></a><nav><a href="#about">关于</a><a href="#craft">技艺</a><a href="#journal">札记</a><a href="#contact">联系</a></nav></header><main id="top"><section className="hero-section"><video className="hero-video" autoPlay muted loop playsInline poster="/media/avatar.jpg"><source src="/media/ink-background.mp4" type="video/mp4" /></video><div className="hero-wash" /><div className="hero-content"><p className="eyebrow">PERSONAL NOTEBOOK · 2026</p><h1>守静<span>致虚</span></h1><p className="hero-lead">软件开发 · 前端 · 后端 · 移动 · 云端 · 创意编程</p><p className="hero-intro">吾名 守静致虚，习技之人。主业软件开发，涉前端、后端、移动及云端诸端，亦好创意编程。此间所录，乃平日学思与项目之迹，聊以自省，亦愿与同道共析</p><a className="ink-link" href="#about">向下探索 ↓</a></div></section>
<section id="about" className="section about-section"><Reveal><p className="section-kicker">01 / ABOUT</p><div className="about-grid"><div className="portrait-frame"><Image src="/media/avatar.jpg" alt="守静致虚头像" width={940} height={940} priority /></div><div><p className="section-kicker">技之所重</p><h2>用户体验为本，<em>代码视为艺。</em></h2><p className="body-copy">用户体验为本，代码视为艺，求精求雅；常怀好奇，日学不辍；乐与开源，知无不言；遇事求新，不拘故常</p></div></div></Reveal></section>
<section id="craft" className="section craft-section"><Reveal><p className="section-kicker">02 / CRAFT</p><h2>技术领域，<em>所学所用。</em></h2></Reveal><div className="craft-grid">{[['前端开发','现代框架：Vue.js 3、React 18、Qwik、SolidJS','构建工具：TypeScript、Vite、Webpack、Rollup','UI/UX设计：关注用户体验和界面设计，追求美学与功能的平衡','移动端：Flutter、React Native、Tauri'],['后端开发','系统编程：Rust、Node.js、Python、Go','API设计：RESTful API、GraphQL、微服务架构','数据库：PostgreSQL、MySQL、MongoDB、Redis'],['移动开发','跨平台：Flutter、Dart、React Native','原生开发：Android、Kotlin、iOS、Swift','性能优化：关注应用性能、内存管理和用户体验'],['开发工具','版本控制：Git、GitHub Actions、GitLab CI','代码质量：ESLint、Prettier、Husky、Commitlint','项目管理：敏捷开发、团队协作、文档编写']].map((item, index) => <Reveal key={item[0]} delay={index * .08}><article className="craft-card"><span>0{index + 1}</span><h3>{item[0]}</h3>{item.slice(1).map((line) => <p key={line}>{line}</p>)}</article></Reveal>)}</div></section>
<section id="journal" className="section journal-section"><Reveal><p className="section-kicker">03 / JOURNAL</p><h2>项目与写作，<em>留下痕迹。</em></h2><div className="journal-list"><article className="journal-item"><span>项目阅历</span><p>曾为企业建内部系统，亦维护开源数件；私暇则自研小作，试验新思；亦参与社区，贡献薄力</p></article><article className="journal-item"><span>写作之余</span><p>编程之外，亦喜笔耕。或撰教程，或记项目得失，或论架构之道，或录生活所感</p></article></div></Reveal></section>
<section id="contact" className="section contact-section"><Reveal><p className="section-kicker">04 / CONTACT</p><h2>联系吾，<em>幸会。</em></h2><p className="body-copy">如果你对我的工作感兴趣，或者有任何问题、建议，欢迎通过以下方式联系我：</p><div className="contact-pair"><a href="https://github.com/kar32224-png" target="_blank" rel="noreferrer"><small>GitHub</small><strong>kar32224-png ↗</strong></a><a href="mailto:1755070122@qq.com"><small>邮箱</small><strong>1755070122@qq.com ↗</strong></a></div><p className="quote">感谢拨冗垂阅，愿有所益<br />“虚静以通，神明其德”</p></Reveal></section></main><footer><span>© 2026 守静致虚</span><span>墨青水墨 · 东方美学与现代技术</span></footer></div>; }
